version: 0.2

phases:
  build:
    commands:
      - echo "Build started at $(date)"
      - mkdir -p output
      - cp -r "AWS PROJECT/project-09/portfolio-repo/." output/
      - echo "Files copied successfully"
      - ls -la output

artifacts:
  base-directory: output
  files:
    - '**/*'
